baseURL = "https://raf-97414.github.io/"
languageCode = "en-us"
title = "Rafelia"
enableRobotsTxt = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
[[menu.main]]
    name = "Articles"
    url = "/articles"
    weight = 20
[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 30
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 40
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 50

[params]
    name = "Rafelia"
    description = "Building Apps"
    github = "raf-97414"
    x = "Rafelia97"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "rose-pine-moon"
    lineNos = true

[taxonomies]
    tag = "tags"
